### ISSUE TITLE
Only working with local neutrino install?

### ISSUE THREAD

**Issue by krisimmig** [factorial-io/factorial-frontend-stack#17]
I tried to run this with a global neutrino install (8.3.0) but that doesn´t work.

`12:37:56 > yarn start
yarn run v1.7.0
$ yarn run neutrino start --use @factorial/frontend-stack-core
error Command "neutrino" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

Adding neutrino locally with `yarn add neutrino`for example works though. Not sure if it is as intended?

**Comment by mlnmln** [comment]
@krisimmig Adding neutrino to the dev dependencies of a project is the preferred way for installation. I forgot to add that to the docs, thanks for the hint. compare to e.g. https://neutrinojs.org/packages/web/
