### ISSUE TITLE
eslint config is not correctly exposed to IDEs

### ISSUE THREAD

**Issue by krisimmig** [factorial-io/factorial-frontend-stack#19]
I would be interested if anyone can get the linting working correctly in an IDE.

I tried to add the `.eslintrc.js` file as described [here](https://neutrinojs.org/packages/eslint/#eslintrc-config).
If I understand what is happening there correctly, this file should export a valid eslint config with all settings that are used in the neutrino middlewares.

I get this error when eslint tries to load the config:
_Cannot read config file: /Users/kris/code/fe-stack-test/.eslintrc.js Error: Cannot find module '.neutrinorc.js'_

Is this working in atom, vs code or sublime for anyone?

**Comment by jlnschfr** [comment]
No, same error here. VS Code is throwing this error.
`[Error - 10:33:11 AM] Error: ESLint configuration in /.../.eslintrc.js is invalid:
	- Unexpected top-level property "exclude".`

**Comment by mlnmln** [comment]
Can confirm, will investigate. 
https://github.com/neutrinojs/neutrino/pull/703
Might help.

**Comment by mlnmln** [comment]
@krisimmig This is fixed in https://github.com/factorial-io/factorial-frontend-stack/releases/tag/%40factorial%2Ffrontend-stack-core%400.2.1 Please verify and close.

**Comment by krisimmig** [comment]
It only works when I add a file:
`/.neutrinorc.js`

With this content (taken from core/examples):

`module.exports = {
  use: [
    "@factorial/frontend-stack-core"
  ]
};`

**Comment by mlnmln** [comment]
I added usage examples to https://github.com/factorial-io/factorial-frontend-stack/tree/master/examples/core. 

Yes, there is a dependency to a .neutrinorc.js currently in it.

**Comment by mlnmln** [comment]
@krisimmig I added your findings to the installation docs, for now we have a dependency to `.neutrinorc.js`.
