### ISSUE TITLE
Document custom entry point

### ISSUE THREAD

**Issue by MiguelCarogar** [factorial-io/factorial-frontend-stack#20]
Could be good documenting how we can set a custom "entry point" instead of ./src/index.js.

Maybe we could add in the Readme something like this:

Add in the .neutrinorc.js this code if our entry point is ./source/index.js:

```
module.exports = {
  use: [
    "@factorial/frontend-stack-core"
  ],
  options: {
    source: "source",
    output: "source/build", // NB: The whole build needs to be under version control currently.
    mains: {
      index: "index.js"
    }
  }
};
```

**Comment by mlnmln** [comment]
@MiguelCarogar 

It's in the neutrino docs. https://neutrinojs.org/customization/#optionssource
I'll add a reference to the docs in the projects readme. 
Thanks for letting me know.
