### ISSUE TITLE
Default eslint env should be `browser`

### ISSUE THREAD

**Issue by mlnmln** [factorial-io/factorial-frontend-stack#22]
IS: 
Currently no default env is set. This leads to lint errors (window, document) when migrating existing projects. 

SHOULD: 
The default evironment should be `browser`.

**Comment by mgrsskls** [comment]
cli is fine for me now, but Sublime still complains about `window`, `document`, `fetch` etc. not being defined. I didn't change any of provided rc files, so basic setup.

**Comment by mlnmln** [comment]
@mgrsskls This should be fixed in https://github.com/factorial-io/factorial-frontend-stack/releases/tag/%40factorial%2Ffrontend-stack-core%400.3.1

Working in VS code on my local.
