### ISSUE TITLE
include() in yaml files not working

### ISSUE THREAD

**Issue by krisimmig** [factorial-io/factorial-frontend-stack#35]
There seems to be a problem when using the patternlab `--watch` task and using `include()` in YAML files.

Already bug reported for this in the data-transform plugin used for this:
https://github.com/aleksip/plugin-data-transform/issues/16

I think for now we have to configure this differently, not using watch task but `php core/console --generate` everytime there is a file change.

**Comment by mlnmln** [comment]
@krisimmig I think the "fix" here is to not use the `--watch` flag, but rather create our own watcher and then trigger a fresh build on file change.
