### ISSUE TITLE
Errors when generating patternlab

### ISSUE THREAD

**Issue by krisimmig** [factorial-io/factorial-frontend-stack#37]
There are still errors when generating patternlab witht he new filewathcer plugin and `php core/console --generate` in the frontend-stack-pattern-lab package.

**To reproduce:**
- Start the watch process with `yarn run neutrino start`
- Change a file that is compiled by babel (JS or CSS)
- Change a file that is compiled by patternlab (YAML or TWIG)

**Result:**
The patternlab generate commands runs twice and errors the second time because of unremovable/unlinkable files.

**Should be:**
`php core/console --generate` only runs once on file change.

**Comment by mlnmln** [comment]
@krisimmig Could it be that the CSS / JS build is still running while the PL build trigger starts?

**Comment by mlnmln** [comment]
@krisimmig Can you confirm that this is fixed now?

**Comment by krisimmig** [comment]
@mlnmln Yes, I tested it already, looks good.
